### PR TITLE
disable updates toggle

### PR DESCRIPTION
**Pull request by dd-dreams**
This is not tested, but I don't see any reason why it shouldn't work.

Solves: #69

### CODE REVIEW

**Comment by thestinger** [comment]
@dd-dreams This doesn't look right and it's going to need to be tested.

**Comment by dd-dreams** [comment]
Could you reference what is not right?
For the testing I've been meaning to turn this into a draft.

**Comment by thestinger** [comment]
You're disabling the method for registering the periodic job for updates, not disabling updates. It will still be scheduled and will still be running.

**Comment by dd-dreams** [comment]
You mean that download will still occur but won't be applied?

**Comment by thestinger** [comment]
No.

**Comment by dd-dreams** [comment]
I guess the `if` statement should be moved/cloned to `onStartJob`, since that's where the Service Intent is.

**Comment by thestinger** [comment]
It's currently disabling registering the periodic job which schedules updates. If it's already registered, it will still be running. Doing this right is more complex than an if statement in these methods. The job shouldn't be scheduled if updates are completely disabled.

This also isn't the way we want to approach adding this feature and the current proposal would be encouraging people to disable updates completely where they won't even be informed an update is available. It's not going to be accepted even if it's implemented correctly. Implementing this in a way that will be accepted means setting it up so that people can still have update notifications without automatic updates. There are a lot of things to consider as part of making the UI. It's not really a good place to start.

**Comment by dd-dreams** [comment]
> It's currently disabling registering the periodic job which schedules updates. If it's already registered, it will still be running. Doing this right is more complex than an if statement in these methods.

I thought the users could just restart but I guess a `changeListener` could be added to this toggle.

I understand, currently, Updater never notifies if a new update is available (looking at NotificationHandler), but immediately starts the update. I could start working on this.

I guess the checklist is just:

- [X] Add a toggle.
- [ ] Listen to changes of the toggle.
- [ ] Add a notification when a new update is available.

**Pull request closed without merging**
